spring.output.ansi.enabled=always


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/sharebuy?stringtype=unspecified
spring.datasource.username=sharebuy
spring.datasource.password=sharebuy!@#

# DDL (Data Definition Language) ??
spring.jpa.hibernate.ddl-auto=update

# SQL ?? ? ???
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ??? ?? (????? ??? ??)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Open Session In View ????
spring.jpa.open-in-view=false

server.port=9011