spring.output.ansi.enabled=always
########################################
#				Database 			   #
########################################
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/sharebuy?stringtype=unspecified
spring.datasource.username=sharebuy
spring.datasource.password=sharebuy!@#